spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 413730
    url: jdbc:mysql://127.0.0.1:3306/miso?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  batch:
    job:
      enabled: true
      name: ${job.name:NONE}
    jdbc:
      initialize-schema: always # Batch 테이블 자동 생성 여부

springdoc:
  packages-to-scan: capstone.miso.dishcovery.application.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui.html # default url: http://127.0.0.1:8080/swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none # tag, operation ??? ??
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: true
  cache:
    disabled: true

key:
  workbook:
    jwt.secret: o8TaeVoSDlxsfpYYFtpNElEPhMp7MvvrSnYQYgKrylMBNGPDqE
jwt:
  expire:
    access: 1
    refresh: 30
    day: 3