spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 413730
    url: jdbc:mysql://127.0.0.1:3306/miso?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            user-name-attribute: id
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-name-attribute: response
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
        registration:
          kakao:
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-id: e8435cddee04055cd1bade598c5fdf10
            client-secret: Ms3I3UjuwEdEIsERyipgSIzstRbjIBDt
            client-authentication-method: POST
            scope:
              - profile_nickname
              - account_email
          naver:
            client-name: naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            client-id: CHfkQ7PXzJ1jm2TlvzCu
            client-secret: a1APsmXML2
            scope:
              - email
              - nickname

springdoc:
  packages-to-scan: com.example.workbook.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui.html # default url: http:127.0.0.1:8080/swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none # tag, operation ??? ??
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: true
  cache:
    disabled: true

key:
  workbook:
    jwt.secret: o8TaeVoSDlxsfpYYFtpNElEPhMp7MvvrSnYQYgKrylMBNGPDqE
jwt:
  expire:
    access: 1
    refresh: 30
    day: 3