package capstone.miso.dishcovery.domain.keyword;

public enum KeywordSet {
    BREAKFAST, LUNCH, DINNER,
    SPRING, SUMMER, FALL, WINTER,
    UNDER_COST_10000, UNDER_COST_20000, UNDER_COST_30000, OVER_COST_30000,
    UNDER_PARTICIPANTS_5, UNDER_PARTICIPANTS_10, UNDER_PARTICIPANTS_20, OVER_PARTICIPANTS_20

}