package capstone.miso.dishcovery.domain.keyword;

public enum KeywordSet {
    BREAKFAST, LUNCH, DINNER,
    SPRING, SUMMER, FALL, WINTER, FOUR_SEASONS,
    UNDER_COST_8000, UNDER_COST_15000, UNDER_COST_25000, OVER_COST_25000,
    UNDER_PARTICIPANTS_5, UNDER_PARTICIPANTS_10, UNDER_PARTICIPANTS_20, OVER_PARTICIPANTS_20,
    HIGH_TOTAL_COST, HIGH_TOTAL_PARTICIPANTS, HIGH_TOTAL_VISITED
}